Rain drops game
AlekseyGrimm/rsschool-cv pull request #17
Opened 2020-12-29 07:03 UTC by AlekseyGrimm

https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/raindrops.md

2020-12-29 13:15 UTC, y-solovey commented
Do you use the file `RainDrops_Game/sounds/sea.mp3` ?

2021-01-06 14:44 UTC, y-solovey requested changes

2021-01-06 14:44 UTC, y-solovey commented on RainDrops_Game/style.css
> +* {
Do we use this file?

2021-01-06 14:44 UTC, y-solovey commented on RainDrops_Game/indexGame.html
> +        <audio id="soundTrue" src="./sounds/trueAnswer.mp3"></audio>
where we use **sea.mp3** file?

2021-01-06 14:44 UTC, y-solovey commented on RainDrops_Game/main.js
> +  function getRandomNumber(min, max) {
please move functions out of `getRandomEquation`

2021-01-06 14:44 UTC, y-solovey commented on RainDrops_Game/main.js
> +  function removeDrop() {
move function out

2021-01-06 14:44 UTC, y-solovey commented on RainDrops_Game/main.js
> +  if (result.textContent.length > 5) {
why we need this line?

2021-01-06 14:44 UTC, y-solovey commented on RainDrops_Game/indexGame.html
> +        <audio id="sound" src="./sounds/sea.mp3"></audio>
should we add `loop` attribute here?

2021-01-06 14:44 UTC, y-solovey commented on RainDrops_Game/main.js
> +    song.stop();
`audio` does not have `stop` method

2021-01-06 14:44 UTC, y-solovey commented on RainDrops_Game/main.js
> +  const zero = result.textContent === "0";
why we need this line?

2021-01-11 09:02 UTC, AlekseyGrimm commented on RainDrops_Game/indexGame.html
> +        <audio id="soundTrue" src="./sounds/trueAnswer.mp3"></audio>
update this code

2021-01-11 09:02 UTC, AlekseyGrimm commented on RainDrops_Game/style.css
> +* {
delete

2021-01-11 09:05 UTC, AlekseyGrimm commented on RainDrops_Game/main.js
> +  function getRandomNumber(min, max) {
update this code

2021-01-11 09:12 UTC, AlekseyGrimm commented on RainDrops_Game/main.js
> +  if (result.textContent.length > 5) {
without this function, all pressed numbers are displayed

2021-01-11 09:12 UTC, AlekseyGrimm commented on RainDrops_Game/main.js
> +  if (result.textContent.length > 5) {
shrink the window and see

2021-01-11 09:14 UTC, AlekseyGrimm commented on RainDrops_Game/indexGame.html
> +        <audio id="sound" src="./sounds/sea.mp3"></audio>
I think that it is not

2021-01-11 09:18 UTC, AlekseyGrimm commented on RainDrops_Game/main.js
> +    song.stop();
pardon)))) I'm add pause( )

2021-01-14 15:13 UTC, y-solovey requested changes

2021-01-14 15:13 UTC, y-solovey commented on RainDrops_Game/main.js
> +  div.className = "raindrop";
please use `div.classList.add("raindrop")`

2021-01-14 15:13 UTC, y-solovey commented on RainDrops_Game/style.css
> +body {
this file does not included in html

2021-01-14 15:13 UTC, y-solovey commented on RainDrops_Game/main.js
> +  function removeDrop() {
try to create `function removeDrop(currentId, up) {}` and move it up

2021-01-14 15:13 UTC, y-solovey commented on RainDrops_Game/gamePlace.css
> +    transform: translateY(-35%);
why we need this line?

2021-01-14 15:13 UTC, y-solovey commented on RainDrops_Game/main.js
> +  }, 2500);
please add "Back" button

2021-01-25 15:22 UTC, AlekseyGrimm commented on RainDrops_Game/main.js
> +  function removeDrop() {
update this code

2021-01-27 13:57 UTC, AlekseyGrimm commented on RainDrops_Game/indexGame.html
> +        <audio id="sound" src="./sounds/sea.mp3"></audio>
update

2021-01-27 14:03 UTC, AlekseyGrimm commented on RainDrops_Game/main.js
> +  div.className = "raindrop";
update

2021-01-27 14:08 UTC, AlekseyGrimm commented on RainDrops_Game/style.css
> +body {
delete this

2021-01-27 14:09 UTC, AlekseyGrimm commented on RainDrops_Game/gamePlace.css
> +    transform: translateY(-35%);
update code

2021-01-27 14:09 UTC, AlekseyGrimm commented on RainDrops_Game/main.js
> +  }, 2500);
well done

2021-02-04 19:00 UTC, AlekseyGrimm commented on RainDrops_Game/main.js
> +  const zero = result.textContent === "0";
I'm fix this code

2021-02-11 15:03 UTC, y-solovey requested changes

2021-02-11 15:03 UTC, y-solovey commented on RainDrops_Game/main.js
> +const playButton = document.getElementById('.control__play-button');
why we need this const?

2021-02-11 15:06 UTC, AlekseyGrimm commented on RainDrops_Game/main.js
> +const playButton = document.getElementById('.control__play-button');
delete this const

2021-04-13 19:21 UTC, closed without merging