Meditation_app_master
AlekseyGrimm/rsschool-cv pull request #7
Opened 2020-11-22 22:03 UTC by AlekseyGrimm

https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-3-meditation-app-20

2020-12-09 15:07 UTC, y-solovey requested changes

2020-12-09 15:07 UTC, y-solovey commented on Audio-App/app.js
> +    console.log("ciao")
please remove logs

2020-12-09 15:07 UTC, y-solovey commented on Audio-App/app.js
> +song.ontimeupdate = function() {
please use adding listener `song.addEventListener('timeupdate', (event) => {
...
});`

2020-12-09 15:07 UTC, y-solovey commented on Audio-App/app.js
> +    video.src = this.getAttribute("data-video");
please use dataset

2020-12-16 18:55 UTC, AlekseyGrimm commented on Audio-App/app.js
> +song.ontimeupdate = function() {
done

2020-12-16 18:55 UTC, AlekseyGrimm commented on Audio-App/app.js
> +    console.log("ciao")
done

2020-12-18 07:49 UTC, y-solovey approved these changes

2020-12-28 15:06 UTC, AlekseyGrimm commented on Audio-App/app.js
> +    video.src = this.getAttribute("data-video");
done

2020-12-28 15:15 UTC, merged